// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Squares.Infrastructure.Contexts;

#nullable disable

namespace Squares.Infrastructure.Migrations
{
    [DbContext(typeof(PointsDbContext))]
    [Migration("20251104175012_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Squares.Domain.Entities.Point", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("PointListId")
                        .HasColumnType("int");

                    b.Property<int>("X")
                        .HasColumnType("int");

                    b.Property<int>("Y")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PointListId");

                    b.ToTable("Points");
                });

            modelBuilder.Entity("Squares.Domain.Entities.PointList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("PointLists");
                });

            modelBuilder.Entity("Squares.Domain.Entities.Point", b =>
                {
                    b.HasOne("Squares.Domain.Entities.PointList", null)
                        .WithMany("Points")
                        .HasForeignKey("PointListId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Squares.Domain.Entities.PointList", b =>
                {
                    b.Navigation("Points");
                });
#pragma warning restore 612, 618
        }
    }
}
